import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import Navbar from "@/components/Navbar";
import ToasterProvider from "@/providers/ToasterProvider";
import ToasterHandler from "@/components/FlashNotice/ToasterHandler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="min-h-dvh">
      <body className={`${inter.className} bg-yellow-200 text-blue-700`}>
        <ToasterProvider>
          <ApolloWrapper>

            <Navbar></Navbar>
            <div className="pt-20">
              {children}
            </div>
          </ApolloWrapper>
          <ToasterHandler></ToasterHandler>
        </ToasterProvider>
      </body>
    </html>
  );
}
